services:
  #traefik:
   # image: traefik:v3.3
    #container_name: traefik
    #command:
     # - "--api.insecure=true"
      #- "--providers.docker=true"
      #- "--providers.docker.exposedbydefault=false"
     # - "--entrypoints.web.address=:80"
    #ports:
     # - "80:80"
     # - "8080:8080"
    #volumes:
     # - "/var/run/docker.sock:/var/run/docker.sock:ro"
    #networks:
    #  - web

  server:
    build:
      context: .
    ports:
     - "8085:80"  # Enlever ce port en phase de prod
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web
    #labels:
     # - "traefik.enable=true"
      #- "traefik.http.routers.ecoride.rule=Host(`ecoride-hauts-de-france.site`)"
      #- "traefik.http.routers.ecoride.entrypoints=web"
      #- "traefik.http.services.ecoride.loadbalancer.server.port=80"

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ecoride-db-data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  mongo:
    image: mongo
    restart: always  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ecoride-mongo-data:/data/db
    expose:
      - "27017"
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - web

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8087:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - web

volumes:
  ecoride-db-data:
  ecoride-mongo-data:

networks:
  web:
    external: false  # pour la prod mettre external: true
